Handling categorial data

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']
])

In [4]:
df.columns = ['color', 'size', 'price', 'classlabel']

In [5]:
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

Mapping ordinal features

In [6]:
size_mapping = {
    'XL': 3,
    'L': 2,
    'M': 1
}

In [7]:
df['size'] = df['size'].map(size_mapping)

In [8]:
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [14]:
size_mapping.items()

[('M', 1), ('L', 2), ('XL', 3)]

In [11]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}

In [15]:
inv_size_mapping

{1: 'M', 2: 'L', 3: 'XL'}

In [16]:
import numpy as np

In [21]:
class_mapping = {label: idx for idx,label in enumerate(np.unique(df['classlabel']))}

In [22]:
class_mapping # can be used to manually map the labels to integers

{'class1': 0, 'class2': 1}

Use LabelEncoder to encode class labels

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
class_le = LabelEncoder()

In [26]:
y = class_le.fit_transform(df['classlabel'].values)

In [27]:
y

array([0, 1, 0])

In [29]:
class_le.inverse_transform(y)

/Users/huilong/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array(['class1', 'class2', 'class1'], dtype=object)

Performing one-hot encoding on nominal features

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
ohe = OneHotEncoder(categorical_features=[0])

In [35]:
X = df[['color', 'size', 'price']].values

In [38]:
X

array([['green', 1, 10.1],
       ['red', 2, 13.5],
       ['blue', 3, 15.3]], dtype=object)

In [37]:
color_le = LabelEncoder()

In [39]:
X[:, 0] = color_le.fit_transform(X[:, 0])

In [40]:
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [43]:
ohe.fit_transform(X).toarray() # toarray get matrix representation of the sparse matrix

array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])